import path from "node:path";
import fs from "node:fs/promises";

export type FactoryChatCodexArtifactPaths = {
  readonly root: string;
  readonly promptPath: string;
  readonly lastMessagePath: string;
  readonly stdoutPath: string;
  readonly stderrPath: string;
  readonly manifestPath: string;
  readonly contextPackPath: string;
  readonly resultPath: string;
  readonly memoryScriptPath: string;
  readonly memoryConfigPath: string;
};

export const factoryChatCodexArtifactPaths = (
  dataDir: string,
  jobId: string,
): FactoryChatCodexArtifactPaths => {
  const root = path.join(dataDir, "factory-chat", "codex", jobId);
  return {
    root,
    promptPath: path.join(root, "prompt.md"),
    lastMessagePath: path.join(root, "last-message.txt"),
    stdoutPath: path.join(root, "stdout.log"),
    stderrPath: path.join(root, "stderr.log"),
    manifestPath: path.join(root, "manifest.json"),
    contextPackPath: path.join(root, "context-pack.json"),
    resultPath: path.join(root, "result.json"),
    memoryScriptPath: path.join(root, "memory.cjs"),
    memoryConfigPath: path.join(root, "memory-scopes.json"),
  };
};

export const readTextTail = async (filePath: string, maxChars: number): Promise<string | undefined> => {
  const text = await fs.readFile(filePath, "utf-8").catch(() => "");
  const trimmed = text.trim();
  if (!trimmed) return undefined;
  return trimmed.length <= maxChars ? trimmed : `...${trimmed.slice(trimmed.length - maxChars + 3)}`;
};

export const buildFactoryMemoryScriptSource = (configPath: string): string => {
  const normalizedConfigPath = configPath.replace(/\\/g, "\\\\");
  return [
    "#!/usr/bin/env bun",
    `const fs = require("node:fs");`,
    `const { execFileSync } = require("node:child_process");`,
    `const config = JSON.parse(fs.readFileSync(${JSON.stringify(normalizedConfigPath)}, "utf-8"));`,
    `const args = process.argv.slice(2);`,
    `const compact = (value, maxChars) => value.length <= maxChars ? value : \`\${value.slice(0, Math.max(0, maxChars - 1))}…\`;`,
    `const formatTree = (nodes, depth = 0) => (nodes || []).flatMap((node) => {`,
    `  const indent = "  ".repeat(depth);`,
    `  const head = \`\${indent}- \${node.taskId}: \${node.title} [\${node.status}]\${node.candidateStatus ? \` · candidate \${node.candidateStatus}\` : ""}\`;`,
    `  const note = node.memorySummary ? \`\${indent}  memory: \${node.memorySummary}\` : "";`,
    `  return [head, note, ...formatTree(node.children || [], depth + 1)].filter(Boolean);`,
    `});`,
    `const runReceipt = (receiptArgs) => {`,
    `  const raw = execFileSync("receipt", receiptArgs, { encoding: "utf-8", maxBuffer: 16 * 1024 * 1024 });`,
    `  return JSON.parse(raw || "{}");`,
    `};`,
    `const resolveScope = (key) => config.scopes.find((scope) => scope.key === key || scope.scope === key);`,
    `const formatEntries = (entries) => (entries || []).map((entry) => \`- \${entry.text}\${entry.tags?.length ? \` [\${entry.tags.join(", ")}]\` : ""}\`).join("\\n");`,
    `const command = args[0] || "overview";`,
    `if (command === "context") {`,
    `  const maxChars = Number(args[1] || config.defaultMaxChars || 2800) || 2800;`,
    `  const pack = config.contextPackPath ? JSON.parse(fs.readFileSync(config.contextPackPath, "utf-8")) : undefined;`,
    `  if (!pack) {`,
    `    process.stdout.write("No recursive context pack found.\\n");`,
    `    process.exit(0);`,
    `  }`,
    `  const lines = [`,
    `    \`Objective: \${pack.title}\`,`,
    `    pack.mode ? \`Mode: \${pack.mode}\` : "",`,
    `    \`Task: \${pack.task.taskId} · \${pack.task.title} [\${pack.task.status}]\`,`,
    `    pack.profile ? \`Profile: \${pack.profile.rootProfileLabel} (\${pack.profile.rootProfileId})\` : "",`,
    `    pack.memory?.overview ? \`Overview: \${pack.memory.overview}\` : "",`,
    `    pack.contextSources?.profileSkillRefs?.length ? \`Profile skills: \${pack.contextSources.profileSkillRefs.join(", ")}\` : "",`,
    `    pack.helperCatalog?.selectedHelpers?.length ? "Checked-in helpers:" : "",`,
    `    ...(pack.helperCatalog?.selectedHelpers || []).flatMap((entry) => [\`- \${entry.id}: \${entry.description}\`, \`  manifest: \${entry.manifestPath}\`, \`  entrypoint: \${entry.entrypointPath}\`]),`,
    `    pack.integration?.status ? \`Integration: \${pack.integration.status}\${pack.integration.lastSummary ? \` · \${pack.integration.lastSummary}\` : ""}\` : "",`,
    `    pack.relatedTasks?.length ? "Related task context:" : "",`,
    `    ...(pack.relatedTasks || []).map((task) => \`- \${task.taskId} [\${task.relations.join(", ")}] · \${task.title} [\${task.status}]\${task.candidateStatus ? \` · candidate \${task.candidateStatus}\` : ""}\${task.memorySummary ? \` · \${task.memorySummary}\` : ""}\`),`,
    `    pack.dependencyTree?.length ? "Dependencies:" : "",`,
    `    ...formatTree(pack.dependencyTree || []),`,
    `    pack.candidateLineage?.length ? "Candidate lineage:" : "",`,
    `    ...(pack.candidateLineage || []).map((candidate) => \`- \${candidate.candidateId} [\${candidate.status}]\${candidate.summary ? \` · \${candidate.summary}\` : ""}\`),`,
    `    pack.recentReceipts?.length ? "Recent receipts:" : "",`,
    `    ...(pack.recentReceipts || []).map((receipt) => \`- \${receipt.type}: \${receipt.summary}\`),`,
    `    pack.objectiveSlice?.frontierTasks?.length ? "Objective frontier:" : "",`,
    `    ...(pack.objectiveSlice?.frontierTasks || []).map((task) => \`- \${task.taskId} · \${task.title} [\${task.status}]\${task.memorySummary ? \` · \${task.memorySummary}\` : ""}\`),`,
    `    pack.objectiveSlice?.recentCompletedTasks?.length ? "Recent completed tasks:" : "",`,
    `    ...(pack.objectiveSlice?.recentCompletedTasks || []).map((task) => \`- \${task.taskId} · \${task.title} [\${task.status}]\${task.memorySummary ? \` · \${task.memorySummary}\` : ""}\`),`,
    `    pack.objectiveSlice?.integrationTasks?.length ? "Integration tasks:" : "",`,
    `    ...(pack.objectiveSlice?.integrationTasks || []).map((task) => \`- \${task.taskId} · \${task.title} [\${task.status}]\${task.memorySummary ? \` · \${task.memorySummary}\` : ""}\`),`,
    `    pack.objectiveSlice?.objectiveMemorySummary ? \`Objective memory: \${pack.objectiveSlice.objectiveMemorySummary}\` : "",`,
    `    pack.objectiveSlice?.integrationMemorySummary ? \`Integration memory: \${pack.objectiveSlice.integrationMemorySummary}\` : "",`,
    `    pack.objectiveSlice?.recentObjectiveReceipts?.length ? "Objective-wide receipts:" : "",`,
    `    ...(pack.objectiveSlice?.recentObjectiveReceipts || []).map((receipt) => \`- \${receipt.type}: \${receipt.summary}\`),`,
    `  ].filter(Boolean);`,
    `  process.stdout.write(compact(lines.join("\\n"), maxChars) + "\\n");`,
    `  process.exit(0);`,
    `}`,
    `if (command === "objective") {`,
    `  const maxChars = Number(args[1] || 1800) || 1800;`,
    `  const pack = config.contextPackPath ? JSON.parse(fs.readFileSync(config.contextPackPath, "utf-8")) : undefined;`,
    `  if (!pack?.objectiveSlice) {`,
    `    process.stdout.write("No objective slice found.\\n");`,
    `    process.exit(0);`,
    `  }`,
    `  const lines = [`,
    `    \`Objective: \${pack.title}\`,`,
    `    pack.mode ? \`Mode: \${pack.mode}\` : "",`,
    `    pack.profile ? \`Profile: \${pack.profile.rootProfileLabel} (\${pack.profile.rootProfileId})\` : "",`,
    `    pack.objectiveSlice.objectiveMemorySummary ? \`Objective memory: \${pack.objectiveSlice.objectiveMemorySummary}\` : "",`,
    `    pack.objectiveSlice.integrationMemorySummary ? \`Integration memory: \${pack.objectiveSlice.integrationMemorySummary}\` : "",`,
    `    pack.objectiveSlice.frontierTasks?.length ? "Frontier tasks:" : "",`,
    `    ...(pack.objectiveSlice.frontierTasks || []).map((task) => \`- \${task.taskId} · \${task.title} [\${task.status}]\${task.memorySummary ? \` · \${task.memorySummary}\` : ""}\`),`,
    `    pack.objectiveSlice.integrationTasks?.length ? "Integration tasks:" : "",`,
    `    ...(pack.objectiveSlice.integrationTasks || []).map((task) => \`- \${task.taskId} · \${task.title} [\${task.status}]\${task.memorySummary ? \` · \${task.memorySummary}\` : ""}\`),`,
    `    pack.objectiveSlice.recentCompletedTasks?.length ? "Recent completed tasks:" : "",`,
    `    ...(pack.objectiveSlice.recentCompletedTasks || []).map((task) => \`- \${task.taskId} · \${task.title} [\${task.status}]\${task.memorySummary ? \` · \${task.memorySummary}\` : ""}\`),`,
    `    pack.objectiveSlice.recentObjectiveReceipts?.length ? "Recent objective receipts:" : "",`,
    `    ...(pack.objectiveSlice.recentObjectiveReceipts || []).map((receipt) => \`- \${receipt.type}: \${receipt.summary}\`),`,
    `  ].filter(Boolean);`,
    `  process.stdout.write(compact(lines.join("\\n"), maxChars) + "\\n");`,
    `  process.exit(0);`,
    `}`,
    `if (command === "overview") {`,
    `  const query = (args[1] || config.defaultQuery || "").trim();`,
    `  const maxChars = Number(args[2] || config.defaultMaxChars || 2400) || 2400;`,
    `  const perScopeMax = Math.max(180, Math.floor(maxChars / Math.max(1, config.scopes.length)));`,
    `  const blocks = config.scopes.map((scope) => {`,
    `    const result = runReceipt(["memory", "summarize", scope.scope, "--query", query || scope.defaultQuery || "", "--limit", String(config.defaultLimit || 6), "--max-chars", String(perScopeMax)]);`,
    `    const summary = typeof result.summary === "string" ? result.summary.trim() : "";`,
    `    return summary ? \`## \${scope.label}\\n\${summary}\` : "";`,
    `  }).filter(Boolean);`,
    `  const output = blocks.length ? compact(blocks.join("\\n\\n"), maxChars) : "No memory entries found.";`,
    `  process.stdout.write(output + "\\n");`,
    `  process.exit(0);`,
    `}`,
    `if (command === "scope") {`,
    `  const scope = resolveScope(args[1]);`,
    `  if (!scope) throw new Error("unknown memory scope");`,
    `  const query = (args[2] || scope.defaultQuery || config.defaultQuery || "").trim();`,
    `  const maxChars = Number(args[3] || config.defaultMaxChars || 1400) || 1400;`,
    `  const result = runReceipt(["memory", "summarize", scope.scope, "--query", query, "--limit", String(config.defaultLimit || 6), "--max-chars", String(maxChars)]);`,
    `  process.stdout.write(((typeof result.summary === "string" ? result.summary : "") || "No memory entries found.") + "\\n");`,
    `  process.exit(0);`,
    `}`,
    `if (command === "search") {`,
    `  const scope = resolveScope(args[1]);`,
    `  if (!scope) throw new Error("unknown memory scope");`,
    `  const query = args[2] || "";`,
    `  if (!query.trim()) throw new Error("search requires query");`,
    `  const limit = Number(args[3] || config.defaultLimit || 6) || 6;`,
    `  const result = runReceipt(["memory", "search", scope.scope, "--query", query, "--limit", String(limit)]);`,
    `  process.stdout.write((formatEntries(result.entries) || "No memory entries found.") + "\\n");`,
    `  process.exit(0);`,
    `}`,
    `if (command === "read") {`,
    `  const scope = resolveScope(args[1]);`,
    `  if (!scope) throw new Error("unknown memory scope");`,
    `  const limit = Number(args[2] || config.defaultLimit || 6) || 6;`,
    `  const result = runReceipt(["memory", "read", scope.scope, "--limit", String(limit)]);`,
    `  process.stdout.write((formatEntries(result.entries) || "No memory entries found.") + "\\n");`,
    `  process.exit(0);`,
    `}`,
    `if (command === "commit") {`,
    `  const scope = resolveScope(args[1]);`,
    `  if (!scope) throw new Error("unknown memory scope");`,
    `  const text = args.slice(2).join(" ").trim();`,
    `  if (!text) throw new Error("commit requires text");`,
    `  const result = runReceipt(["memory", "commit", scope.scope, "--text", text]);`,
    `  process.stdout.write(JSON.stringify(result, null, 2) + "\\n");`,
    `  process.exit(0);`,
    `}`,
    `throw new Error(\`unknown memory command '\${command}'\`);`,
    "",
  ].join("\n");
};
